### ISSUE TITLE
Issue with multiple subcommands example from the docs

### ISSUE THREAD

**Issue by paolodina** [bckohan/django-typer#26]
Hi and thanks for this wonderful package, very useful.

But... even trying with copy and paste, I got a problem reproducing the example in the docs, I'll paste the traceback.

```bash
❯ python manage.py foobar
Traceback (most recent call last):

  File "/tmp/dtyper/manage.py", line 22, in <module>
    main()

  File "/tmp/dtyper/manage.py", line 18, in main
    execute_from_command_line(sys.argv)

  File "/tmp/.venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()

  File "/tmp/.venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)

  File "/tmp/.venv/lib/python3.10/site-packages/django_typer/__init__.py", line 1905, in run_from_argv
    return super().run_from_argv(argv)

  File "/tmp/.venv/lib/python3.10/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)

  File "/tmp/.venv/lib/python3.10/site-packages/django_typer/__init__.py", line 1929, in execute
    result = super().execute(*args, **options)

  File "/tmp/.venv/lib/python3.10/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)

  File "/tmp/.venv/lib/python3.10/site-packages/django_typer/__init__.py", line 1887, in handle
    return self.typer_app(

click.exceptions.UsageError: Missing command.
```

With `rich`:

```bash
❯ python manage.py foobar
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /tmp/dtyper/manage.py:22 in <module>                                                             │
│                                                                                                  │
│   19                                                                                             │
│   20                                                                                             │
│   21 if __name__ == "__main__":                                                                  │
│ ❱ 22 │   main()                                                                                  │
│   23                                                                                             │
│                                                                                                  │
│ ╭────────────────────────────────────── locals ───────────────────────────────────────╮          │
│ │ main = <function main at 0x7f09c175bd90>                                            │          │
│ │   os = <module 'os' from '/home/paolo/.pyenv/versions/3.10.4/lib/python3.10/os.py'> │          │
│ │  sys = <module 'sys' (built-in)>                                                    │          │
│ ╰─────────────────────────────────────────────────────────────────────────────────────╯          │
│                                                                                                  │
│ /tmp/dtyper/manage.py:18 in main                                                                 │
│                                                                                                  │
│   15 │   │   │   "available on your PYTHONPATH environment variable? Did you "                   │
│   16 │   │   │   "forget to activate a virtual environment?"                                     │
│   17 │   │   ) from exc                                                                          │
│ ❱ 18 │   execute_from_command_line(sys.argv)                                                     │
│   19                                                                                             │
│   20                                                                                             │
│   21 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ ╭────────────────────────────────────── locals ──────────────────────────────────────╮           │
│ │ execute_from_command_line = <function execute_from_command_line at 0x7f09c071edd0> │           │
│ ╰────────────────────────────────────────────────────────────────────────────────────╯           │
│                                                                                                  │
│ /tmp/.venv/lib/python3.10/site-packages/django/core/management/__init__.py:442 in                │
│ execute_from_command_line                                                                        │
│                                                                                                  │
│   439 def execute_from_command_line(argv=None):                                                  │
│   440 │   """Run a ManagementUtility."""                                                         │
│   441 │   utility = ManagementUtility(argv)                                                      │
│ ❱ 442 │   utility.execute()                                                                      │
│   443                                                                                            │
│                                                                                                  │
│ ╭─────────────────────────────────── locals ────────────────────────────────────╮                │
│ │    argv = ['manage.py', 'foobar']                                             │                │
│ │ utility = <django.core.management.ManagementUtility object at 0x7f09c1653f70> │                │
│ ╰───────────────────────────────────────────────────────────────────────────────╯                │
│                                                                                                  │
│ /tmp/.venv/lib/python3.10/site-packages/django/core/management/__init__.py:436 in execute        │
│                                                                                                  │
│   433 │   │   elif self.argv[1:] in (["--help"], ["-h"]):                                        │
│   434 │   │   │   sys.stdout.write(self.main_help_text() + "\n")                                 │
│   435 │   │   else:                                                                              │
│ ❱ 436 │   │   │   self.fetch_command(subcommand).run_from_argv(self.argv)                        │
│   437                                                                                            │
│   438                                                                                            │
│   439 def execute_from_command_line(argv=None):                                                  │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │       args = []                                                                              │ │
│ │    options = Namespace(settings=None, pythonpath=None, args=[])                              │ │
│ │     parser = CommandParser(prog='manage.py', usage='%(prog)s subcommand [options] [args]',   │ │
│ │              description=None, formatter_class=<class 'argparse.HelpFormatter'>,             │ │
│ │              conflict_handler='error', add_help=False)                                       │ │
│ │       self = <django.core.management.ManagementUtility object at 0x7f09c1653f70>             │ │
│ │ subcommand = 'foobar'                                                                        │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /tmp/.venv/lib/python3.10/site-packages/django_typer/__init__.py:1905 in run_from_argv           │
│                                                                                                  │
│   1902 │   │   :param argv: the arguments to pass to the command                                 │
│   1903 │   │   """                                                                               │
│   1904 │   │   with self:                                                                        │
│ ❱ 1905 │   │   │   return super().run_from_argv(argv)                                            │
│   1906 │                                                                                         │
│   1907 │   def execute(self, *args, **options):                                                  │
│   1908 │   │   """                                                                               │
│                                                                                                  │
│ ╭────────────────────────────────── locals ──────────────────────────────────╮                   │
│ │ argv = ['manage.py', 'foobar']                                             │                   │
│ │ self = <myapp.management.commands.foobar.Command object at 0x7f09c0229e40> │                   │
│ ╰────────────────────────────────────────────────────────────────────────────╯                   │
│                                                                                                  │
│ /tmp/.venv/lib/python3.10/site-packages/django/core/management/base.py:413 in run_from_argv      │
│                                                                                                  │
│   410 │   │   args = cmd_options.pop("args", ())                                                 │
│   411 │   │   handle_default_options(options)                                                    │
│   412 │   │   try:                                                                               │
│ ❱ 413 │   │   │   self.execute(*args, **cmd_options)                                             │
│   414 │   │   except CommandError as e:                                                          │
│   415 │   │   │   if options.traceback:                                                          │
│   416 │   │   │   │   raise                                                                      │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │        args = []                                                                             │ │
│ │        argv = ['manage.py', 'foobar']                                                        │ │
│ │ cmd_options = {                                                                              │ │
│ │               │   'version': None,                                                           │ │
│ │               │   'verbosity': 1,                                                            │ │
│ │               │   'settings': '',                                                            │ │
│ │               │   'pythonpath': None,                                                        │ │
│ │               │   'traceback': False,                                                        │ │
│ │               │   'no_color': False,                                                         │ │
│ │               │   'force_color': False,                                                      │ │
│ │               │   'skip_checks': False                                                       │ │
│ │               }                                                                              │ │
│ │     options = _ParsedArgs(version=None, verbosity=1, settings='', pythonpath=None,           │ │
│ │               traceback=False, no_color=False, force_color=False, skip_checks=False)         │ │
│ │      parser = <django_typer.TyperParser object at 0x7f09bfb975e0>                            │ │
│ │        self = <myapp.management.commands.foobar.Command object at 0x7f09c0229e40>            │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /tmp/.venv/lib/python3.10/site-packages/django_typer/__init__.py:1929 in execute                 │
│                                                                                                  │
│   1926 │   │   if options.get("force_color", None) is not None:                                  │
│   1927 │   │   │   self.force_color = options["force_color"]                                     │
│   1928 │   │   with self:                                                                        │
│ ❱ 1929 │   │   │   result = super().execute(*args, **options)                                    │
│   1930 │   │   self.no_color = no_color                                                          │
│   1931 │   │   self.force_color = force_color                                                    │
│   1932 │   │   return result                                                                     │
│                                                                                                  │
│ ╭───────────────────────────────────── locals ──────────────────────────────────────╮            │
│ │        args = ()                                                                  │            │
│ │ force_color = False                                                               │            │
│ │    no_color = False                                                               │            │
│ │     options = {                                                                   │            │
│ │               │   'version': None,                                                │            │
│ │               │   'verbosity': 1,                                                 │            │
│ │               │   'settings': '',                                                 │            │
│ │               │   'pythonpath': None,                                             │            │
│ │               │   'traceback': False,                                             │            │
│ │               │   'no_color': False,                                              │            │
│ │               │   'force_color': False,                                           │            │
│ │               │   'skip_checks': False                                            │            │
│ │               }                                                                   │            │
│ │        self = <myapp.management.commands.foobar.Command object at 0x7f09c0229e40> │            │
│ ╰───────────────────────────────────────────────────────────────────────────────────╯            │
│                                                                                                  │
│ /tmp/.venv/lib/python3.10/site-packages/django/core/management/base.py:459 in execute            │
│                                                                                                  │
│   456 │   │   │   │   self.check(tags=self.requires_system_checks)                               │
│   457 │   │   if self.requires_migrations_checks:                                                │
│   458 │   │   │   self.check_migrations()                                                        │
│ ❱ 459 │   │   output = self.handle(*args, **options)                                             │
│   460 │   │   if output:                                                                         │
│   461 │   │   │   if self.output_transaction:                                                    │
│   462 │   │   │   │   connection = connections[options.get("database", DEFAULT_DB_ALIAS)]        │
│                                                                                                  │
│ ╭─────────────────────────────────── locals ────────────────────────────────────╮                │
│ │    args = ()                                                                  │                │
│ │ options = {                                                                   │                │
│ │           │   'version': None,                                                │                │
│ │           │   'verbosity': 1,                                                 │                │
│ │           │   'settings': '',                                                 │                │
│ │           │   'pythonpath': None,                                             │                │
│ │           │   'traceback': False,                                             │                │
│ │           │   'no_color': False,                                              │                │
│ │           │   'force_color': False,                                           │                │
│ │           │   'skip_checks': False                                            │                │
│ │           }                                                                   │                │
│ │    self = <myapp.management.commands.foobar.Command object at 0x7f09c0229e40> │                │
│ ╰───────────────────────────────────────────────────────────────────────────────╯                │
│                                                                                                  │
│ /tmp/.venv/lib/python3.10/site-packages/django_typer/__init__.py:1887 in handle                  │
│                                                                                                  │
│   1884 │   │   :return: Any object returned by the Typer app                                     │
│   1885 │   │   """                                                                               │
│   1886 │   │   with self:                                                                        │
│ ❱ 1887 │   │   │   return self.typer_app(                                                        │
│   1888 │   │   │   │   args=args,                                                                │
│   1889 │   │   │   │   standalone_mode=False,                                                    │
│   1890 │   │   │   │   supplied_params=options,                                                  │
│                                                                                                  │
│ ╭─────────────────────────────────── locals ────────────────────────────────────╮                │
│ │    args = ()                                                                  │                │
│ │ options = {                                                                   │                │
│ │           │   'version': None,                                                │                │
│ │           │   'verbosity': 1,                                                 │                │
│ │           │   'settings': '',                                                 │                │
│ │           │   'pythonpath': None,                                             │                │
│ │           │   'traceback': False,                                             │                │
│ │           │   'no_color': False,                                              │                │
│ │           │   'force_color': False,                                           │                │
│ │           │   'skip_checks': False                                            │                │
│ │           }                                                                   │                │
│ │    self = <myapp.management.commands.foobar.Command object at 0x7f09c0229e40> │                │
│ ╰───────────────────────────────────────────────────────────────────────────────╯                │
│                                                                                                  │
│ /tmp/.venv/lib/python3.10/site-packages/typer/main.py:328 in __call__                            │
│                                                                                                  │
│ /tmp/.venv/lib/python3.10/site-packages/typer/main.py:311 in __call__                            │
│                                                                                                  │
│ /tmp/.venv/lib/python3.10/site-packages/click/core.py:1157 in __call__                           │
│                                                                                                  │
│ /tmp/.venv/lib/python3.10/site-packages/typer/core.py:778 in main                                │
│                                                                                                  │
│ /tmp/.venv/lib/python3.10/site-packages/typer/core.py:216 in _main                               │
│                                                                                                  │
│ /tmp/.venv/lib/python3.10/site-packages/click/core.py:1668 in invoke                             │
│                                                                                                  │
│ /tmp/.venv/lib/python3.10/site-packages/click/core.py:684 in fail                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
UsageError: Missing command.

/tmp/dtyper via 🐍 v3.10.4 (.venv) 
```

**Comment by bckohan** [comment]
Hi Paolo!

Thanks for this report and giving the library a try 😊.

When you add subcommands to a management command you'll need to invoke the command like so:

```
<manage script> <command module name> [command arguments] <subcommand name> [subcommand arguments]
```

It's unclear to me if fubar is your subcommand or your module name - if its a subcommand your second argument will need to be the module name and you'll need to invoke it like: ```./manage.py <module name> fubar``` otherwise you'll need to invoke it like ```./manage.py fubar <subcommand name>```

Subcommands are given the same name as the function or whatever name you pass to the name parameter of @command().

**If this doesn't address your issue please also post your module name, code and the --help output if you can get it.**

There's an additional complexity to be aware of here too. There is an upstream limitation from typer that if you add any subcommands you can no longer have an unnamed root command - so if you have several subcommands and a handle() method, that handle() method will also turn into a subcommand and be given the name of the module by default.

That said there is a bug here - I would not expect you to get a stack trace for a misspecification of the command invocation unless --traceback was supplied. I'll open an issue and get that fixed.

Thank you!

**Comment by paolodina** [comment]
This is the code.

```python
# myapp/management/commands/foobar.py

import typing as t
from typer import Argument
from django_typer import TyperCommand, command

class Command(TyperCommand):
    """
    A command that defines subcommands.
    """

    def handle(self):
        print("HI")

    @command()
    def create(
        self,
        name: t.Annotated[
            str,
            Argument(help="The name of the object to create."),
        ],
    ):
        """
        Create an object.
        """
        print(f"Obj {name} created...")

    @command()
    def delete(
        self,
        id: t.Annotated[
            int,
            Argument(help="The id of the object to delete."),
        ],
    ):
        """
        Delete an object.
        """

        print(f"Obj {id} deleted...")
```

My outputs:
```sh
$ ./manage.py foobar --help
# as expected with `foobar`, `create` and `delete`

$ ./manage.py foobar delete 10
Obj 10 deleted...

$ ./manage.py foobar create dummy
Obj dummy created...

❯ ./manage.py foobar foobar
HI

❯ ./manage.py foobar
# this gives the long traceback of the first message in this issue and this:
# UsageError: Missing command.

```

So, thanks for the clarifications, everything seems fine to me except that when I run `./manage.py foobar` I'd prefer the users of the CLI to see a friendly message. Now that #27 is alive :-) I think we can close this issue.

**Comment by bckohan** [comment]
It seems like you expected handle() to be a root command somewhat separate from create and delete. This is exactly what I was concerned about in #23 but its not clear if its possible. As noted in #23 the closest I can come has a major problem that any arguments specified on handle() must then also be supplied when create or delete is called.

**Can I ask if you wanted this behavior for a real use case or if you were just testing things out?**

**Comment by paolodina** [comment]
It was a real use case related to the initial issue I mentioned. I was trying to catch the exception in the `handle` method.

```python
from click.exceptions import UsageError

def handle(self, *args, **options):
    try:
        return super().execute(*args, **options)
    except UsageError:
        self.print_help(self.name, "not clear what")
```

When I attempted to do the same in the `execute` method, it seemed to be effective, at least as a workaround.
